title: Alex Gautier
email: alex.gautier@guide-gnss.com
# logo: assets/img/headshot-bw.png
description: "Data Scientist in Geolocation"

theme: jekyll-theme-minimal
markdown: kramdown
timezone: FR
allow_search_engines: true
plugins:
  - jekyll-avatar
  - jekyll-feed

author:
  name     : Alex Gautier"
  avatar   : "assets/img/headshot-bw.png"
  bio      : "Data Scientist in Geolocation"
  location : "Toulouse, France"
  links:
     label: "linkedIn"
     icon: "assets/img/linkedin-icon.png"
     url: "https://www.linkedin.com/in/alexgautier/"
