title: Alex Gautier
email: alex.gautier@guide-gnss.com
# logo: assets/img/headshot-bw.png
theme: jekyll-theme-minimal
markdown: kramdown
timezone: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

author:
  name     : Alex Gautier"
  avatar   : "assets/img/headshot-bw.png"
  bio      : "Data Scientist in Geolocation"
  location : "Toulouse, France"
  links:
   - label: "linkedIn"
     icon: "assets/img/linkedin-icon.png"
     url: "https://www.linkedin.com/in/alexgautier/"
